export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCESS = "USER_SIGNIN_SUCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCESS = "USER_REGISTER_SUCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_FROGET_EMAIL_REQUEST = "USER_FROGET_EMAIL_REQUEST";
export const USER_FROGET_EMAIL_SUCESS = "USER_FROGET_EMAIL_SUCESS";
export const USER_FROGET_EMAIL_FAIL = "USER_FROGET_EMAIL_FAIL";

export const USER_RESET_PASSWORD_REQUEST = "USER_RESET_PASSWORD_REQUEST";
export const USER_RESET_PASSWORD_SUCESS = "USER_RESET_PASSWORD_SUCESS";
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCESS = "USER_DETAILS_SUCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCESS = "USER_UPDATE_PROFILE_SUCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";
